USE EVOLUTION

--Valida si existe la tabla llamada 'USUARIO' y la crea si es necesario
IF OBJECT_ID('USUARIO', 'U') IS  NULL
BEGIN
	CREATE TABLE USUARIO
	(
		UsuID INT IDENTITY(1,1),
		UsuNombre VARCHAR(50) NOT NULL,
		UsuPass VARCHAR(20) NOT NULL,
		CONSTRAINT PK_USUARIO PRIMARY KEY (UsuID)
	)
END

--Valida si existe la tabla llamada 'PRODUCTO' y la crea si es necesario
IF OBJECT_ID('PRODUCTO', 'U') IS  NULL
BEGIN
	CREATE TABLE PRODUCTO
	(
		ProID INT IDENTITY(1,1),
		ProDesc VARCHAR(50) NOT NULL,
		ProValor MONEY NOT NULL,
		CONSTRAINT PK_PRODUCTO PRIMARY KEY (ProID)
	)
END

--Valida si existe la tabla llamada 'PEDIDO' y la crea si es necesario
IF OBJECT_ID('PEDIDO', 'U') IS  NULL
BEGIN
	CREATE TABLE PEDIDO
	(
		PedID INT IDENTITY(1,1),
		PedUsu INT NOT NULL,
		PedProd INT NOT NULL,
		PedVrUnit MONEY NOT NULL,
		PedCant FLOAT NOT NULL,
		PedSubTot MONEY NOT NULL,
		PedIVA FLOAT NOT NULL,
		PedTotal MONEY NOT NULL
		CONSTRAINT PK_PEDIDO PRIMARY KEY (PedID),
		CONSTRAINT FK_PEDIDO_PRODUCTO FOREIGN KEY (PedProd) REFERENCES PRODUCTO (ProID),
		CONSTRAINT FK_PEDIDO_USUARIO FOREIGN KEY (PedUsu) REFERENCES USUARIO (UsuID)
	)
END